### ISSUE TITLE
Consider creating a CI runner for MinGW

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#645]

**Comment by ahayzen-kdab** [comment]
@Be-ing any ideas how easy this might or might not be ? 

Looks like this would need to be adjusted to be only msvc
```yml
    # Required for CMake to find Ninja
    - name: "[Windows] Set up MSVC Developer Command Prompt"
      if: runner.os == 'Windows'
      uses: seanmiddleditch/gha-setup-vsdevenv@v3
```

And we would need a new block here which doesn't use `cl` ?

```yml
          - name: Windows 2022 (MSVC) Qt6
            os: windows-2022
            qt_version: 6
            ctest_args: --exclude-regex '^(reuse_lint|cpp_clang_format|.*valgrind)$'
            exe_suffix: .exe
            qt_qpa_platform: windows
            compiler_cache_path: C:\Users\runneradmin\AppData\Local\Mozilla\sccache\cache
            cargo_dir: C:\Users\runneradmin\.cargo
            cc: cl
            cxx: cl
            # The D drive runs out of space when building dependencies with vcpkg.
            workspace: C:\cxx-qt
```

And we would need to install `mingw` from somewhere ? (would this be from vcpkg or is there a github action we can use or is it already installed?)
